{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dispatch-operator
  labels:
    {{- include "dispatch.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dispatch.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: /metrics
{{- end }}
