---
apiVersion: v1
kind: Service
metadata:
  name: dispatch-operator
  labels:
    {{- include "dispatch.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "dispatch.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: metrics
    - name: gateway
      port: {{ .Values.gateway.port }}
      targetPort: gateway
