---
name: ci

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make generate manifests
      - run: git diff --exit-code
      - run: make vet
      - run: make test
      - run: make build
      - uses: azure/setup-helm@v4
      - run: make chart
